#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    schintacloud-app:
        image: schintacloud
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://schintacloud-mysql:3306/schintacloud?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=schintacloud-cassandra
            - JHIPSTER_SLEEP=80 # gives time for uaa and the Cassandra cluster to start and execute the migration scripts
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=schintacloud-elasticsearch:9300
        ports:
            - 9000:9000
    schintacloud-mysql:
        extends:
            file: mysql.yml
            service: schintacloud-mysql
    # Uncomment to have Cassandra working with the gateway
    # schintacloud-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: schintacloud-cassandra
    # schintacloud-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: schintacloud-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    schintacloud-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: schintacloud-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
